name: automacao_horta
description: TCC Mobile Client

publish_to: "none"

version: 2.0.3+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  mqtt_client: ^9.6.8
  get: ^4.6.5
  bot_toast: ^4.0.2
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16
  fluttertoast: ^8.0.9
  device_info_plus: ^3.2.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #drop_down_list: ^0.0.2 -
  drop_down_list: #Change to enable widget in dark mode
    path: ./local/drop_down_list-main

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/fruits/

  fonts:
    - family: Bariol
      fonts:
        - asset: assets/fonts/Bariol_Regular_Italic.otf
        - asset: assets/fonts/Bariol_Regular.otf
