// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwbDyCSPFNZEy8x_2j79Mt-iwJxVYGtKA',
    appId: '1:712992465403:web:2dc94c8cab1ec83ce62b5e',
    messagingSenderId: '712992465403',
    projectId: 'iplant-580e3',
    authDomain: 'iplant-580e3.firebaseapp.com',
    storageBucket: 'iplant-580e3.appspot.com',
    measurementId: 'G-5JYC5F9EHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv8ko6EIZw0jLlwOQ8T7sLS42nM7MYpUw',
    appId: '1:712992465403:android:ab3962cf28b7d01be62b5e',
    messagingSenderId: '712992465403',
    projectId: 'iplant-580e3',
    storageBucket: 'iplant-580e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGj__ayrChjjBrsIbeDw0bUw6M84kZFhM',
    appId: '1:712992465403:ios:12d3877733dda7c6e62b5e',
    messagingSenderId: '712992465403',
    projectId: 'iplant-580e3',
    storageBucket: 'iplant-580e3.appspot.com',
    iosClientId: '712992465403-i9a6kugq0uf008ob7jdgcchthf84s5f6.apps.googleusercontent.com',
    iosBundleId: 'uam.tcc.automacaoHorta',
  );
}
